---
- name: Atlas Network bulk machine onboarding
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: [curl]
        state: present
        update_cache: yes

    - name: Stop the Atlas Network Provider service
      ansible.builtin.service:
        name: atlasnetwork-provider
        state: stopped
      when: reset |bool is true
      ignore_errors: true

    - name: Remove the Atlas Network configuration
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.atlas-network"
        state: absent
      when: reset |bool is true
      ignore_errors: true

    - name: Setup
      ansible.builtin.shell: |
        if [ ! -d "{{ ansible_env.HOME }}/.atlas-network" ]; then
          curl -L https://get.atlasnetwork.dev | sh -s - {{ onboarding_key }}
        fi
